services:
  aufgaben-api:
    build:
      context: .
      dockerfile: AufgabenService/AufgabenService.API/Dockerfile
    ports:
      - "5001:8080"
    networks:
      - microservice-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: aufgaben-api

  aufgaben-client:
    build:
      context: ./AufgabenService/AufgabenService.Client
    ports:
      - "5101:80"
    depends_on:
      - aufgaben-api
    networks:
      - microservice-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AufgabenApiUrl=http://aufgaben-api:8080
    container_name: aufgaben-client

  pruefung-api:
    build:
      context: .
      dockerfile: PruefungService/PruefungService.API/Dockerfile
    ports:
      - "5002:8080"
    networks:
      - microservice-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - aufgaben-api
    container_name: pruefung-api

  pruefung-client:
    build:
      context: ./PruefungService/PruefungService.Client
    ports:
      - "5102:80"
    depends_on:
      - pruefung-api
    networks:
      - microservice-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PruefungApiUrl=http://pruefung-api:8080
    container_name: pruefung-client

networks:
  microservice-network:
    driver: bridge